name: hinted_image_picker
description: A Flutter widget wrapping image_picker to show a customizable hint image before selection and a thumbnail after, with hover elevation, ripple, and multi-image support.
version: 0.1.0
homepage: https://github.com/reginhelpsyou-pixel/flutter_hinted_image_picker
repository: https://github.com/reginhelpsyou-pixel/flutter_hinted_image_picker
issue_tracker: https://github.com/reginhelpsyou-pixel/flutter_hinted_image_picker
topics:
  - image-picker
  - widget
  - ui
  - picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  image_picker_platform_interface: ^2.10.0
  plugin_platform_interface: ^2.1.8

flutter: